### ISSUE TITLE
Block Flash Space for FPGA access only

### ISSUE THREAD

**Issue by DavidFederl** [es-ude/elastic-ai.runtime.enV5#235]
- [x] implement function to block from given start sector and given number of bytes
       - return is start address (sector) with guarentee, that wanted number of bytes is blocked 
- [x] Documentation
- [ ] Test

> [!NOTE]
> Could be implemented using block protection. This would require the fpga to have acccess to the password of those protected sectors. To do this we would need changes to the skeleton/middleware

**Comment by HerrCooker** [comment]
@LeoBuron Instead of using a start address given by the user, shouldn't choosing the start point be handled by the file system? Meaning the user just puts in the number of required bytes and gets a start address as a return value.

Maybe that was the idea and my notes from the last meeting are wrong.
